### ISSUE TITLE
Channel field is wrongly passed

### ISSUE THREAD

**Issue by kamvoick** [crazymanish/fastlane-plugin-slack_bot#1]
Hello,

so i've encountered problem with channel field, according to this document https://api.slack.com/methods/chat.postMessage#channels

you can pass as a channel field only formats like:
1. hash symbol - #<your_channel>
2. channel id - C024BE91L
3. user id - U0G9QF9C6

so in your implementation you're adding either # or @ with passed value which prevents from sending it correctly. I've tried passing username with @ in every single way and this doesn't work. Another thing is that default channel also doesn't work, at least when i try leave that field empty.

**Comment by crazymanish** [comment]
Hello @kamvoick 
I notice the bug when we pass channel id - C024BE91L, this plugin is adding extra # 🙈 Possible workaround: Please pass full channel name instead of channel id. see the example below:

You can use one of the below options to use this plugin. 
**Let's assume** that you want to send the message in slack channel name: **#some-testing-channel** (channel id - C024BE91L)

```ruby
# Example1: Sending message to slack channel without # input
post_to_slack(
    message: "Sending testing message",
    channel: "some-testing-channel"
  )

# Example2: Sending message to slack channel without # input
post_to_slack(
    message: "Sending testing message",
    channel: "#some-testing-channel"
  )
Please don't use the channel id - C024BE91L :) 
```

**Let's assume** that you want to send the message in slack user name: **manish.rathi** (user id - U0G9QF9C6)
```ruby
# Example3: Sending message to user-name
post_to_slack(
    message: "Sending testing message",
    channel: "@manish.rathi"
  )

# Example3: Sending message to user-id
post_to_slack(
    message: "Sending testing message",
    channel: "@U0G9QF9C6"
  )
```


> so in your implementation you're adding either # or @ with passed value which prevents from sending it correctly.

The logic is, if the user will not send # then I am appending # (see above Example1)

 > I've tried passing username with @ in every single way and this doesn't work. 

I have just tested and it worked. Are you sure, your SLACK BOT is added to the workspace and has proper permission?

> Another thing is that default channel also doesn't work, at least when i try leave that field empty.

Well when you create SLACK BOT then you can set the default channel, also I will highly recommend to always pass channel name either Example1 or Example2 



I hope this will help you!

**Comment by crazymanish** [comment]
Just now I have tested all the above 4 examples, all examples are working so you should not be blocked to implement anything. I am closing this ticket. 

please feel free to re-open, in case of any issue :)
